### ISSUE TITLE
A carta do Rei está vindo com a inicial C

### ISSUE THREAD

**Issue by VictorQRS** [HermanoLeite/fodinha#1]
A carta do Rei está vindo com a inicial C, no baralho normal não seria a letra K?

**Comment by VictorQRS** [comment]
Após uma pequena pesquisa, achei aqui que existe uma carta chamada Knight que tem a inicial C: `Unicode Character 'PLAYING CARD **KNIGHT** OF HEARTS' (U+1F0BC)`, enquanto existe o código do rei um pouco mais a frente `Unicode Character 'PLAYING CARD **KING** OF HEARTS' (U+1F0BE)`. Esse último tem a inicial K nela.

**Comment by VictorQRS** [comment]
Acredito que só trocar os respectivos unicodes e problema resolvido!

**Comment by VictorQRS** [comment]
@HermanoLeite Como ainda não consegui fazer rodar o projeto na minha máquina, se importaria de fazer PR(teste) ou commitar direto na master 😈?

**Comment by HermanoLeite** [comment]
Massa!! Como ainda está bem no início estou mandando direto na Master. Vou fazer isso hoje! Está difícil de rodar na sua máquina? Está com algum problema?

**Comment by VictorQRS** [comment]
Não, apenas não tive o tempo de configurar. Aí, para resolver a issue o mais rápido possível, já passei a solução ;)

Claro que se estiver sem tempo ou prefira não dar prioridade agora, posso fazer também, só vai levar um tempo até eu fazer rodar na máquina.

**Comment by HermanoLeite** [comment]
Feito
