### ISSUE TITLE
Melhorar a parte visual

### ISSUE THREAD

**Issue by VictorQRS** [HermanoLeite/fodinha#13]
Fazer com que as informações corretas apareçam nas horas corretas.
Colocar zoeiras.

**Comment by HermanoLeite** [comment]
Criar uma área que mostra quantas vidas cada jogador tem, qual o palpite dele, quantas ele fez na rodada, e qual carta ele jogou.

- [ ] Juntar placar rodada com placar jogo
- [ ] Juntar jogada com placar

**Comment by HermanoLeite** [comment]
Tirei o botão da carta. Agora quando pode jogar a carta fica clicavel e quando não pode a carta fica com opacidade reduzida e não clicável

**Comment by HermanoLeite** [comment]
Fazer layout baseado no gartic
