### ISSUE TITLE
Permitir jogador escolher se deseja ver cartinhas

### ISSUE THREAD

**Issue by HermanoLeite** [HermanoLeite/fodinha#19]
Em alguns browsers o unicode das cartinhas não funciona.
Algumas pessoas preferem que não fique mostrando as cartinhas

**Comment by VictorQRS** [comment]
Transformar as cartas em componentes facilitaria esse controle.

**Comment by VictorQRS** [comment]
Poderia ter uma opção (ou algumas) que seria salva nos cookies, que assim que fosse renderizar a carta, poderia ver se ele quer/consegue renderizar a versão unicode.
