### ISSUE TITLE
Criação de board para organização do Kanban

### ISSUE THREAD

**Issue by VictorQRS** [HermanoLeite/fodinha#3]
Como a ideia é fazer os cards do Trello virarem issues, para manter a organização do kanban do Trello, pode ser interessante criar um projeto (automatizado talvez) dentro do Github.

**Comment by HermanoLeite** [comment]
Eu acho que vou criar vários projetos. Organizando as "releases".
Coloco um objetivo. Crio um projeto para ele. E coloco as issues para atingir esses objetivos.
Não sei se faz sentido.

**Comment by VictorQRS** [comment]
Faz sim, já vi isso em vários projetos.

**Comment by VictorQRS** [comment]
@HermanoLeite Vc automatizou o quadro?

**Comment by HermanoLeite** [comment]
Sim sim, na verdade criei no template de quadro automatizado.
