### ISSUE TITLE
Selecao de cores pela paleta de cores

### ISSUE THREAD

**Issue by VictorQRS** [HermanoLeite/fodinha#4]
Jogadores hoje tem de escrever a cor que querem pra eles. Seria mais interessante se eles pudessem escolher a partir de uma paleta de cores e então salvaríamos o código HEX ou RGB ao invés de uma string com a descrição da cor (que pode inclusive não ser uma cor).

**Comment by VictorQRS** [comment]
Sugestão: https://farbelous.io/bootstrap-colorpicker/index.html

**Comment by HermanoLeite** [comment]
Acabei tirando a parte de escolha de cor, não estava fazendo sentido.
