### ISSUE TITLE
site caiu. site fora do ar

### ISSUE THREAD

**Issue by Leonardocatsuraiama** [HermanoLeite/fodinha#43]
Eu e uns amigos estamos testando o jogo a dois dias, hoje dia 03/29 o jogo ficou fora do ar. poderia esta nos ajudando

**Comment by HermanoLeite** [comment]
Fala Leonardo, beleza? Eu acabei derrubando ele porque não estava olhando para isso. Você consegue rodar o jogo apontando para o firestore da sua conta firebase (é de graça e fácil de fazer o setup). Como o modelo de dados é todo no front end facilita. Avisa aí se tiver algo que eu possa ajudar.
